baseURL = "https://techwit2.netlify.app/"
disableLanguages = []
disqusShortname = "techwitke"
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "UA-132349593-10"
languageCode = "en-us"
languageName = "En"
paginate = "10"
summaryLength = "15"
theme = "twentytwenty"
title = "TechWit v0.7"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "blog"
name = "Blog"
weight = 1
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.main]]
URL = "privacy-policy"
name = "Privacy Policy"
weight = "5"
[[menu.main]]
URL = "terms-and-conditions"
name = "Terms and Conditions"
weight = "6"
[[menu.main]]
URL = "newsletter"
name = "Newsletter"
weight = "7"
[[menu.main]]
URL = "advertise-here"
name = "Advertise Here"
weight = "8"
[[menu.main]]
URL = "https://links.collect.chat/5f295075cac8ec33b6a2c151"
name = "Chat with Our Bot"
weight = "9"
[[menu.main]]
URL = "tip-us"
name = "Tip Us Securely"
weight = "10"
[[menu.main]]
URL = "guest-posting"
name = "Guest Post Here"
weight = "11"
[[menu.main]]
URL = "index.xml"
name = "RSS Feed"
weight = "12"
[[menu.main]]
URL = "index.json"
name = "RSS Feed Json"
weight = "13"
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
Images = ["images/hero.webp"]
author = "Admin"
description = "Welcome to The TechWit Ke. Your Trusted Source of Quality Tech, Cybersecurity and Development Tips, Tricks, Tutorials, Reviews, News, Offers and Other Content."
image = ["images/hero.webp"]
[params.banner]
heading = "Quality Tech Content For All"
image = "images/bannersmall.webp"
[params.blog]
heading = "Our Latest Articles"
[params.call_to_action]
button_label = "I Want to Sign Up"
button_url = "/newsletter"
content = "Sign up and stay up to date by receiving quality content such as tips, tricks, news, howto's, insights, deals, savings, promotions, freebies, ebooks and more right in your inbox. Never miss an article or a giveaway. \nBecome a member of our community. Join us!"
enable = true
title = "Sign Up To Our Newsletter"
[params.footer]
content = "We are a Tech, Cybersecurity and Development Blog focused on delivering quality content to keep you updated and well informed. We make sure content is not only trusted but also understandable for all whether tech savvy or not. Get Tips, Tricks, Tutorials, Reviews, News, Offers and More From One Place: TechWit Ke.<br>\n[Privacy Policy](/privacy-policy) | [Terms and Conditions](/terms-and-conditions) | [Advertise Here](/advertise-here)"
copyright = "Copyright &copy; 2020 [TechWit Ke](https://techwit2.netlify.app). All Rights Reserved.  "
email = "[techwit.ke@gmail.com](mailto:techwit.ke@gmail.com?cc=alunje73@gmail.com&subject=From%20Blog%20Footer)"
telephone = "[+ 254 726 024 210](tel:+254726024210)"
title = "About"
[params.gallery]
enable = false
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[params.social]
email = "techwit.ke@gmail.com"
facebook = "https://facebook.com/techwitke"
feed = "https://techwit2.netlify.app/index.xml"
instagram = "https://instagram.com/techwitke"
linkedin = "https://linkedin.com/techwitke"
twitter = "https://twitter.com/techwitke"
whatsapp = "https://chat.whatsapp.com/C7whEtGOcsY3eJU1mbiveB"
[related]
includeNewer = true
threshold = 10
toLower = true
[[related.indices]]
name = "Section"
weight = 200
[[related.indices]]
name = "keywords"
weight = 150
[[related.indices]]
name = "tags"
weight = 300
[[related.indices]]
name = "categories"
weight = 150
[[related.indices]]
name = "date"
weight = 10
[[related.indices]]
name = "author"
weight = 10
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
