baseURL = "https://techwit2.netlify.app/"
disableLanguages = []
disqusShortname = "techwitke"
googleAnalytics = "UA-132349593-10"
languageCode = "en-us"
languageName = "En"
paginate = "7"
summaryLength = "15"
theme = "twentytwenty"
title = "TechWit"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "blog"
name = "Blog"
weight = 1
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.main]]
URL = "privacy-policy"
name = "Privacy Policy"
weight = "5"
[[menu.main]]
URL = "index.xml"
name = "Xml RSS Feed"
weight = "6"
[[menu.main]]
URL = "feed.json"
name = "Json RSS Feed"
weight = "7"
[outputFormats.jsonfeed]
baseName = "feed"
isPlainText = true
mediaType = "application/json"
[outputs]
home = ["HTML", "RSS", "JSON", "jsonfeed"]
[params]
author = "Admin"
description = "Welcome to The TechWit Kenya Blog. Your Source of Cutting Edge Tech, Cybersecurity and Development Content."
[params.banner]
heading = "Quality Tech Content For All"
image = "images/2020-landscape-1-2.png"
[params.blog]
heading = "Our Latest Articles"
[params.call_to_action]
button_label = "I Want to Sign Up"
button_url = "#"
content = "Sign up and stay up to date by receiving quality content such as tips, tricks, news, howto's, insights, deals, savings, promotions and more right in your inbox. Never miss an article or a giveaway. \nBecome a member of our community. Join us!\nAlso download this free <a href=\"#\">Cyber Security Guide For Individuals</a> and protect yourself and data from hackers."
enable = true
title = "Sign Up To Our Newsletter"
[params.footer]
content = "We are a Tech, Cybersecurity and Development Blog focused on delivering quality content to keep you updated and well informed. We make sure content is not only trusted but also understandable for all whether tech savvy or not. Get Tips, Tricks, Tutorials, Reviews, News, Offers and More From One Place: TechWit Ke"
copyright = "Copyright &copy; 2020 [TechWit Ke](https://techwit2.netlify.app). All Rights Reserved. &nbsp; &nbsp;  [Privacy Policy](/privacy-policy) | [Terms and Conditions](#)"
email = "[techwit.ke@gmail.com](mailto:techwit.ke@gmail.com?cc=alunje73@gmail.com&subject=From%20Blog%20Footer)"
telephone = "[+ 254 726 024 210](tel:+254726024210)"
title = "About"
[params.gallery]
enable = false
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[params.social]
email = "techwit.ke@gmail.com"
facebook = "https://facebook.com/techwitke"
instagram = "https://instagram.com/techwitke"
linkedin = "#"
twitter = "https://twitter.com/techwitke"
yelp = "#"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
