baseURL = "https://techwit2.netlify.app/"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "twentytwenty"
title = "TechWit"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Themefisher"
description = "Welcome to TechWit"
[params.banner]
heading = "Get Quality Tech, Cybersecurity and Development Content."
image = "images/2020-landscape-1-2.png"
[params.blog]
heading = "Our Latest Articles"
[params.call_to_action]
button_label = "I Want to Sign Up"
button_url = "#"
content = "Sign up and stay up to date by receiving quality content such as tips, tricks, news, howto's, insights, deals, savings, promotions and more right in your inbox. Never miss an article or a giveaway. \nBecome a member of our community. Join us!\nAlso download this free <a href=\"#\">Cyber Security Guide For Individuals</a> and protect yourself and data from hackers."
enable = true
title = "Sign Up To Our Newsletter"
[params.footer]
address = "Nairobi, Kenya"
content = "We are a Tech, Cybersecurity and  Development Blog focusing on delivering quality content to keep you up to date and informed."
copyright = "Copyright &copy; 2020 [TechWit Kenya](https://techwit2.netlify.app)"
hours = "Blog Availability: 24/7<br><b>Chat<b><br>Monday-Friday: 9:00AM - 4:00PM<br>Saturday and Sunday: 11:00AM - 3:00PM"
title = "About"
[params.gallery]
enable = false
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[params.social]
email = "#"
facebook = "#"
instagram = "#"
linkedin = "#"
twitter = "#"
yelp = "#"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
